language: node_js
node_js: node
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
before_deploy:
  - yarn install
  - yarn build
deploy:
  provider: script
  script: yarn deploy
  on:
    branch: $DEPLOYMENT_BRANCH

